### ISSUE TITLE
Add support for standalone components

### ISSUE THREAD

**Issue by marcjulian** [maplibre/ngx-maplibre-gl#120]
This would enable the `standalone` API for components and directives. Allowing to only import the components needed in the application instead of using `NgxMapLibreGLModule`.

`NgxMapLibreGLModule` should be kept for backwards compatibility and `declarations` would be replaced with `imports`.

Running `ng generate @angular/core:standalone` (https://angular.dev/reference/migrations/standalone) will help with the migration to standalone components.

I would be willing to create a PR.

**Comment by HarelM** [comment]
It would be great if you could submit a PR to solve this.
I would hold off with Angular version 17 ATM to reduce clutter and noise.
