### ISSUE TITLE
Map is not loading after setting up the ngx-maplibre-gl

### ISSUE THREAD

**Issue by ksoni23** [maplibre/ngx-maplibre-gl#13]
I setup the ngx-maplibe-gl as mentioned in the readme

1. Installed the package using **npm install ngx-maplibre-gl maplibre-gl @types/geojson**

2. Added _global style_ as mentioned **@import '~maplibre-gl/dist/maplibre-gl.css';** to styles.scss

3. Updated _polyfills.ts_ with **(window as any).global = window;**

4. Added **_NgxMapboxGLModule_** to app.module.ts

`import { NgxMapLibreGLModule } from 'ngx-maplibre-gl';

@NgModule({
  imports: [
    ...
    NgxMapLibreGLModule
  ]
})
export class AppModule {}`

5.  There is separate module for map pages. Using **<mgl-map>** component to map display component same 

`import { Component } from '@angular/core';

@Component({
  template: `
    <mgl-map
      [style]="'https://demotiles.maplibre.org/style.json'"
      [zoom]="[9]"
      [center]="[-74.5, 40]"
    >
    </mgl-map>
  `,
  styles: [
    `
      mgl-map {
        height: 100%;
        width: 100%;
      }
    `,
  ],
})
export class DisplayMapComponent {}`

6. After serving the app and while loading the map component  **getting following errors and map is not loading up.** 

<img width="1501" alt="Screenshot 2021-09-30 at 12 36 52 PM" src="https://user-images.githubusercontent.com/31221440/135404108-58f7a4f2-4e3f-457c-a116-0694f60fc4dc.png">

### Any hint or suggestions would be really appreciated.
Thanks in advance.

###

**Comment by HarelM** [comment]
Make sure you install maplibre 1.15 as 2.x is still in pre release.
Checkout the demo page, it has a stackblitz edit button to see working code with examples.
Once you make it work please send a PR to update the documentation... :-)

**Comment by ksoni23** [comment]
> Make sure you install maplibre 1.15 as 2.x is still in pre release. Checkout the demo page, it has a stackblitz edit button to see working code with examples. Once you make it work please send a PR to update the documentation... :-)


These are packages config.

`  "@types/geojson": "^7946.0.8",
    "cookie-storage": "^6.1.0",
    "core-js": "^2.5.4",
    "moment": "^2.22.2",
    "ngx-maplibre-gl": "^12.0.0",`

**Comment by HarelM** [comment]
Is this still relevant?

**Comment by HarelM** [comment]
No answer, closing...
