### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by tbo47** [maplibre/ngx-maplibre-gl#130]
the build is working but at runtime I have the following error:
```
ERROR TypeError: Cannot read properties of null (reading 'firstCreatePass')
```
and no map shows up

I run the latest `main`, node v20.10.0, npm 10.2.5.

And I started from a clean install:
```
rm -rf node_modules; npm ci ; npx ng s
```

**Comment by HarelM** [comment]
Which version of maplibre are you using?
Please share a stackblitz with the error.

**Comment by HarelM** [comment]
No response, closing.
