### ISSUE TITLE
Input for mgl-marker rotation missing.

### ISSUE THREAD

**Issue by ctaepper** [maplibre/ngx-maplibre-gl#147]
while there is an input for [rotation alignment](https://maplibre.org/maplibre-gl-js/docs/API/classes/Marker/#setrotationalignment), there is no input for [rotation](https://maplibre.org/maplibre-gl-js/docs/API/classes/Marker/#setrotation). It would be great to have this added.

**Comment by HarelM** [comment]
Feel free to open a PR.

**Comment by ctaepper** [comment]
fair enough 🤓

**Comment by ctaepper** [comment]
@HarelM do you care creating a new release for this feature?

**Comment by HarelM** [comment]
Yes, I just want to see if I can test out the new docs with this release, so it should happen within a few days.
