### ISSUE TITLE
[Help] Customlayer 3d model

### ISSUE THREAD

**Issue by MichalNemec** [maplibre/ngx-maplibre-gl#15]
Hello,
Could you create an example how to include 3d model in this library?

I have trouble with CustomLayerInterface and accesing map + making it more dynamic to load model based on property.

Even if three.js is not possible, then with deck.gl

Thanks!

**Comment by HarelM** [comment]
I haven't done it myself and the closest thing I saw was this example:
https://maplibre.org/maplibre-gl-js-docs/example/add-3d-model/
You can access the map instance from the map component's `mapInstance` property.

**Comment by MichalNemec** [comment]
Okay, will try that.
on another note `Type 'CustomLayerInterface' has no properties in common with type 'Layout'.`
```
<mgl-layer id="3d-models" type="custom" source="earthquakes" [layout]="modelLayout"></mgl-layer>
```
how the html looks like to load the layer?

**Comment by HarelM** [comment]
No Clue, as I said, I haven't tried it.
If you find the answer let me know :-)
You can also ask the authors of the original branch that works with mapbox, maybe they'll have better answer than I do...

**Comment by HarelM** [comment]
Closing...
