### ISSUE TITLE
Clarify repository status

### ISSUE THREAD

**Issue by matkoniecz** [maplibre/ngx-maplibre-gl#16]
>  This branch is 44 commits ahead, 30 commits behind Wykks:master. 

How this repository is related to https://github.com/Wykks/ngx-mapbox-gl ?

Why it exists as fork?

**Comment by hheexx** [comment]
@HarelM 2.0 update expected soon?

**Comment by HarelM** [comment]
Yes, I already created a branch for it, feel free to test it and let me know how it works...

**Comment by hheexx** [comment]
@HarelM can you please update to 2.0 final and publish to npm as prerelase ?

**Comment by HarelM** [comment]
@wipfli can you take a look at the latest publish npm action log?
It seems that I can't publish the package under `@maplibre` for some reason...
P.S. this is the first time I try...

**Comment by HarelM** [comment]
The release failed probably due to this issue:
https://stackoverflow.com/questions/41981686/getting-error-402-while-publishing-package-using-npm
I'll see if I can fix this and release again.

**Comment by HarelM** [comment]
I've published a version under a new name:
@maplibre/ngx-maplibre-gl

Let me know if you experience any issue with it.

**Comment by hheexx** [comment]
@HarelM thanks.
Looks like it crashes my compilation with OOM errors... strange....

**Comment by HarelM** [comment]
I'm able to pass compilation in my project, but mine is relatively small...

**Comment by hheexx** [comment]
Fixed it. I forgot to change package name in angular modules. For some reason that causes OOM errors instead of something more sensible.

Looks like it works except typings problem you already know about.

**Comment by HarelM** [comment]
Closing this issue. Feel free to post here though...
