### ISSUE TITLE
Marker click event trigger underlying layer

### ISSUE THREAD

**Issue by redor85** [maplibre/ngx-maplibre-gl#176]
I am developing a website where polygons are representing landmarks on a map. 

When doing an address search, a marker should be displayed on the found location on the map. 
A click on the marker should delete it. 

The polygons also have a click event so you can go to the detail page of the landmarks. 

Unfortunately, when clicking on the marker, the event of the underlying polygon is also executed. 

The desired behavior would be that only the click event of the marker is executed.

Simple Stackblitz example: https://stackblitz.com/edit/angular-ishur8?file=src%2Fdemo.ts

**Comment by HarelM** [comment]
I believe you should use `$event.stopPropagation();` to achieve the desired behavior.
This is no different than any other UI handling...

**Comment by redor85** [comment]
Thank you @HarelM.

That's of course a valid solution.

I'm working with OpenLayers for so many years. I have to change my way of thinking about web maps using maplibre.

**Comment by HarelM** [comment]
Any chance I can task you with writing a migration guide from open layer to maplibre?
