### ISSUE TITLE
HTML clusters are not working correct

### ISSUE THREAD

**Issue by HarelM** [maplibre/ngx-maplibre-gl#188]
When going to the example page:
https://maplibre.org/ngx-maplibre-gl/demo/ngx-cluster-html

Zooming in to get the cluster expanded - the original cluster are still there.
Zooming out will keep also the clusters that should be removed.

This is how it looks.
![image](https://github.com/user-attachments/assets/c7918d32-254f-49a8-b8c6-08b8407e1adf)

I thought it might be because of the change I made, but reverting it doesn't solve the problem...
CC: @n-elhk @marcjulian

**Comment by marcjulian** [comment]
Looks like this change from #183 is the cause

```diff
- this.subscription.add(
-   this.zone.onMicrotaskEmpty.subscribe(() => this.applyChanges())
- );
+ this.subscription.add(this.applyChanges());
```

**Comment by HarelM** [comment]
I'll let you look into it then as I have little knowledge in this area...

**Comment by marcjulian** [comment]
I would revert this change for now, as I am also not sure what the best approach should be here.

**Comment by n-elhk** [comment]
```
  constructor() {
    const observer = new MutationObserver(() => {
      this.mapService.applyChanges();
    });

    observer.observe(this.element.nativeElement, {
      childList: true,
      subtree: true,
    });

    this.destroyRef.onDestroy(() => observer.disconnect());
  }
```

We can use MutationObserver to replace onMicrotaskEmpty. I tested it works

use it indirective to apply on mapComponent or directly in MapService and replace "this.element.nativeElement" by document

**Comment by HarelM** [comment]
Feel free to open a PR and let me know which you think is better.

**Comment by HarelM** [comment]
@n-elhk I've sent you an invite in case you want to help out maintain this library (which you are doing anyway :-))

**Comment by marcjulian** [comment]
> ```
>   constructor() {
>     const observer = new MutationObserver(() => {
>       this.mapService.applyChanges();
>     });
> 
>     observer.observe(this.element.nativeElement, {
>       childList: true,
>       subtree: true,
>     });
> 
>     this.destroyRef.onDestroy(() => observer.disconnect());
>   }
> ```
> 
> We can use MutationObserver to replace onMicrotaskEmpty. I tested it works
> 
> In directive to apply on MapComponent or directly in MapService and replace "this.element.nativeElement" by document

I also thought about it, what about using `afterRender` to call `applyChanges`.

> The `NgZone.onMicrotaskEmpty` and `NgZone.onStable` observables are most often used to wait for Angular to complete change detection before performing a task. Instead, these can be replaced by `afterNextRender` if they need to wait for a single change detection or `afterRender` if there is some condition that might span several change detection rounds.

This is from the [docs](https://angular.dev/guide/experimental/zoneless#remove-ngzoneonmicrotaskempty-ngzoneonunstable-ngzoneisstable-or-ngzoneonstable) on how to replace `onMicrotaskEmpty`

```ts
// map.component.ts
constructor() {
  afterRender(() => {
      this.mapService.applyChanges();
  });
}
```

Maybe we could also think of a another name for `applyChanges` to better reflect the actual function

**Comment by HarelM** [comment]
Any improvements are welcome, I agree applyChanges is not a great name for this method.

**Comment by n-elhk** [comment]
> > ```
> >   constructor() {
> >     const observer = new MutationObserver(() => {
> >       this.mapService.applyChanges();
> >     });
> > 
> >     observer.observe(this.element.nativeElement, {
> >       childList: true,
> >       subtree: true,
> >     });
> > 
> >     this.destroyRef.onDestroy(() => observer.disconnect());
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We can use MutationObserver to replace onMicrotaskEmpty. I tested it works
> > In directive to apply on MapComponent or directly in MapService and replace "this.element.nativeElement" by document
> 
> I also thought about it, what about using `afterRender` to call `applyChanges`.
> 
> > The `NgZone.onMicrotaskEmpty` and `NgZone.onStable` observables are most often used to wait for Angular to complete change detection before performing a task. Instead, these can be replaced by `afterNextRender` if they need to wait for a single change detection or `afterRender` if there is some condition that might span several change detection rounds.
> 
> This is from the [docs](https://angular.dev/guide/experimental/zoneless#remove-ngzoneonmicrotaskempty-ngzoneonunstable-ngzoneisstable-or-ngzoneonstable) on how to replace `onMicrotaskEmpty`
> 
> ```ts
> // map.component.ts
> constructor() {
>   afterRender(() => {
>       this.mapService.applyChanges();
>   });
> }
> ```
> 
> This also works with the cluster updates on zoom.
> 
> Maybe we could also think of a another name for `applyChanges` to better reflect the actual function

I just looked and tested I think using afterRender is the best solution

**Comment by marcjulian** [comment]
I updated the PR to use `afterRender`
