### ISSUE TITLE
mgl-control not displaying anything

### ISSUE THREAD

**Issue by zelanter** [maplibre/ngx-maplibre-gl#194]
I am still new to this library, so it's highly probable that I am doing something wrong, but controls aren't displaying at all.

`  <mgl-control mglNavigation></mgl-control>`

The rest seems to be working: map is displaying, I can add markers, I can show a popup.

Could I be missing a style or important setup step?

I also tried to add it dynamically through (mapLoad) event using map instance, and it's not showing, so it's most likely a step missing. Maybe documentation tricks me into believing we can have a fully working map using those components only and I missed something very basic.

**Comment by zelanter** [comment]
I inspected the html and controls are there, but with display set to none. If I override that style I can see the controls. I'll review everything to see what I am missing that would explain I have to do this.

**Comment by HarelM** [comment]
Can you provide a stackblitz reproduction? 
You can use the documentation site and click the edit button to see the code.

**Comment by zelanter** [comment]
> Can you provide a stackblitz reproduction? You can use the documentation site and click the edit button to see the code.

I'll try to provide one later today.

Yes, I am aware of the code in the examples, this is exactly what I based my code on.

Another bit of information: I am using Angular 16, and as such am using version 16.x.x and maplibre 3.x.x. Would I be better off using newer versions or they wouldn't work well with Angular 16?

Thanks

**Comment by zelanter** [comment]
I didn't have time to try to replicate in stackblitz. I still don't know why I had to manually set display for it to work, but at this point I'll close this. Thanks
