### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by HarelM** [maplibre/ngx-maplibre-gl#2]
e2e tests are currently broken since I don't have the right map sources to showcase all the options and so the tests fail.
I would like to release an initial version to npm to see that it is working as expected and later on fix these tests...

**Comment by HarelM** [comment]
@klokan any chance to get your help on this?
The purpose of the showcase is to demonstrate maplibre-gl and ngx-maplire on top of it.
What I basically need are some styles json file stored remotely I can use for the demo pages, I currently use only the streets.json, the same one from the maplibre examples, but I would like to showcase other styles if it's OK by you.

**Comment by klokan** [comment]
Looks as a great effort! Thanks for pushing on this.

- Are the demos going to be displayed only on maplibre.org?
(BTW do you know that if you make a `gh-pages` branch for the web pages in any of the maplibre repos - your webpages pushed there are going to be available at http://maplibre.org/ngx-maplibre-gl/ -  similarly as https://maplibre.org/maplibre-gl-js-docs/ is?)

- Why is this repo only a fork?  If you want to make it the official Angular binding for maplibre - just propose a transfer.
- Don't you want to join this Wednesday on the steering commity meetup to do a demo and show it off?

**Comment by HarelM** [comment]
Thanks for the quick response!
* I haven't got to the point where I though about where to host the documentation, but `gh-page` was one of my first thoughts, if it is displayed at maplibre.org it would be great (I didn't know that).
* The original code was not maintained by me and I did try to move the maintainers here, but I guess they are using mapbox so they preferred to stay there. You can read more about it here: https://github.com/Wykks/ngx-mapbox-gl/issues/260
* I'll be joining the Wednesday meeting (hopefully if everything goes as planned), I can probably do a short demo there if there aren't more urgent topics to discuss...

But first thing first, I need to fix the tests, and for that I need a few more styles to be able to switch between them in one of the showcases.

**Comment by HarelM** [comment]
Test that still fail:
* popup-on-click - icon theatre-15 ??
* polygon-popup-on-click - source "composite" not found
* Toggle layers - contours and museums sources - not sure how to easily fix this
