### ISSUE TITLE
About pop up

### ISSUE THREAD

**Issue by Aini452** [maplibre/ngx-maplibre-gl#20]
Hello,

I want to display a pop up on a click on a layer or a marker.
If i know how to implement the event to click, when i close the popup, it never come back.
I think that i need the event emitter popupClose but i didn't succed to implement it. Is it possible to have more documentation or any help ? 

Thank you.

**Comment by HarelM** [comment]
Popup has a close event as can be read here:
https://maplibre.org/ngx-maplibre-gl/doc
I suggest to look at the demo page and documentation again to see some good examples of how to use the code. :-)

**Comment by HarelM** [comment]
Feel free to submit a PR to improve the docs :-)
