### ISSUE TITLE
(Question) Loading dozens of images.

### ISSUE THREAD

**Issue by radekdob** [maplibre/ngx-maplibre-gl#201]
Hi, I need to load many images into map in order to display layer as symbol with custom image source.

Currently I load them on `mapLoad` event with the following sequence:
- `map.loadImage(url)`
- `map.addImage(key, addedImage.data)`

wrapped inside `Promise.all(...)`.

I wonder if there is other more performant way of doing it, any ideas?

Thanks,

**Comment by HarelM** [comment]
Use a sprite... You can you more than one sprite for a map.

**Comment by radekdob** [comment]
Thanks @HarelM, did not know about this function, but in my case it might be not worth to change due to quite dynamic nature of my map, but for more static like assets on map I will probably go with your suggestion :)
