### ISSUE TITLE
Transitionable paint properties

### ISSUE THREAD

**Issue by pflopez** [maplibre/ngx-maplibre-gl#202]
A lot of properties are marked as `Transitionable` on map libre https://maplibre.org/maplibre-style-spec/layers/#fill-opacity but I believe this is missing on this wrapper? I don't see if on https://maplibre.org/ngx-maplibre-gl/API/classes/LayerComponent.html#paint and if I try to add `fill-opacity-transition` for example, I get an error.

Is there a way to set transitions to properties? thank you!

**Comment by HarelM** [comment]
I guess you could use "as any"...? The style spec types generation is not perfect I guess and this is why transitionable is not part of it...
