### ISSUE TITLE
Missing mapbox style support?

### ISSUE THREAD

**Issue by Silinator** [maplibre/ngx-maplibre-gl#204]
Is it only possible to use maptiler styles?

The mapbox url format is not supportet and when using the https://api.mapbox.com/styles/v1/mapbox/streets-v12?access_token=pk.xxx url as style the map keeps white. without any errors.

Is there a different way to add mapbox styles? Since Wykks/ngx-mapbox-gl did support it.

**Comment by HarelM** [comment]
If you are using mapbox you should use the original fork (ngx-mapbix-gl). 
If you are using maplibre you should use this fork.
Maplibre doesn't support mapbox url out of the box. There might be a plugin to accommodate for that, but I'm not sure how well it works.

**Comment by Silinator** [comment]
Thanks for very fast answer
Sadly the original fork (ngx-mapbox-gl) seems to be abandoned.
