### ISSUE TITLE
Unable to draw polygons

### ISSUE THREAD

**Issue by papastepano** [maplibre/ngx-maplibre-gl#36]
Is drawing a polygon somehow possible? Or is implementing it on the agenda?

**Comment by HarelM** [comment]
You can implement this, but it's not part of this library. This is simply a wrapper of maplibre for angular.

**Comment by papastepano** [comment]
Can you please give me a simple example or point me somehow in the right direction?

**Comment by HarelM** [comment]
Start with the demo page, there are many examples there, you can click on edit to open survivors stackblitz to see the code.
I world start with simply displaying a polygon and then see how you can complicate it to allow editing etc.
This is my route editing interaction, which is the data layer and not the presentation layer.
https://github.com/IsraelHikingMap/Site/blob/main/IsraelHiking.Web/src/application/components/intercations/route-edit-route.interaction.ts

**Comment by HarelM** [comment]
This is not an issue, so I'm closing, feel free to continue the conversation here though.
