### ISSUE TITLE
Search address like mglGeocoder in <mgl-control>

### ISSUE THREAD

**Issue by mateusscheper** [maplibre/ngx-maplibre-gl#37]
Hello! 

I saw that geocoder was removed from maplibre. Is there another way to search for an address and display it on the map?

Thank you!

**Comment by HarelM** [comment]
You can still add this control, but it's not part this library in order to reduce dependencies.

**Comment by Bohdan159** [comment]
Hello!

How I can add geocoder control?
You mean manually by myself, adding this directive to my codebase, right?

Thank you!

**Comment by HarelM** [comment]
You can use the mapInstance and use the regular code written in the geocoder docs or write a directive of your own

**Comment by Bohdan159** [comment]
Understand, thank you!
