### ISSUE TITLE
Module can only be default-imported using the 'allowSyntheticDefaultImports' flag

### ISSUE THREAD

**Issue by damian-kociszewski** [maplibre/ngx-maplibre-gl#44]
A minor issue that can be fixed by setting the "_allowSyntheticDefaultImports_" flag to _true_ in tsconfig.json

`
Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:3:8 - error TS1259: Module '"<my-path>/node_modules/@types/mapbox__point-geometry/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

3 import Point from '@mapbox/point-geometry';
         ~~~~~

  node_modules/@types/mapbox__point-geometry/index.d.ts:46:1
    46 export = Point;
       ~~~~~~~~~~~~~~~

This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
`

**Comment by HarelM** [comment]
Not sure what's needed here.
If you think this should be part of the docs please create a PR.
`Point` is a maplibre-gl-js dependency that can't be removed and export as default (the "old way").

**Comment by Ste-denko** [comment]
I am facing the same problem after following the exact documentation of ngx-maplibre-gl.
Any solution for this?

**Comment by HarelM** [comment]
See the following example (missing css though):
https://stackblitz.com/edit/angular-ivy-fpge8r?file=src%2Findex.html

**Comment by HarelM** [comment]
@Ste-denko, @damian-kociszewski isn't adding `allowSyntheticDefaultImports` to tsconfig.json solves this?

**Comment by Ste-denko** [comment]
Adding allowSyntheticDefaultImports to tsconfig.json fixes it.

@HarelM could you provide some background info about this.
What is the parameter allowSyntheticDefaultImports for?
To which value should it be set in the tsconfig.json (true/false)?

**Comment by HarelM** [comment]
It's worth reading this in the typescript manual as I might not explain it very good.
The bottom line is that the `geomerty-point` is exported in a way that requires this flag and the typings for the `geomerty-point` honors that type of export.
This package is used in the maplibre-gl package which is also needed in order to work with this package.
I hope this explain this well enough, but if not I advise to read about this flag in the manual...

**Comment by Ste-denko** [comment]
@HarelM thank you.
For me this is fixed now and could be closed.

**Comment by Sampath-Lokuge** [comment]
Hi @HarelM 

Please update the doc too. I was not able to find this on the readme: https://github.com/maplibre/ngx-maplibre-gl

This works for me:

`tsconfig.json`

```
 "angularCompilerOptions": {
   ...
    "allowSyntheticDefaultImports": true
  }
```

**Comment by HarelM** [comment]
@Sampath-Lokuge feel free to open a PR to improve the docs.
