### ISSUE TITLE
npm package for version 13.0.0

### ISSUE THREAD

**Issue by dogukan10** [maplibre/ngx-maplibre-gl#53]
I can see that there was a release for v13.0.0 but no npm package is available in https://www.npmjs.com/package/ngx-maplibre-gl

Is it possible to publish a package for v13.0.0 which solves the rxjs dependency conflict in my project. Thanks in advance.

**Comment by HarelM** [comment]
This is a link to a deprecated package...
Checkout the readme:
`npm install @maplibre/ngx-maplibre-gl`
