### ISSUE TITLE
Merge changes from upstream

### ISSUE THREAD

**Issue by HarelM** [maplibre/ngx-maplibre-gl#6]
There has been many changes in upstream that needs to be incorporated into this library to support latest features.
The fork date is: Jun 5, 2021.
geo-coder was removed from this lib so it's a question if to add it as a separate library or not as they did with the upstream fork.

Other fixes are probably needed/required, angular 12 is probably one of the important ones...

**Comment by aprilmay** [comment]
I'll have a look, i feel that it will be like cherry picking from upstream changes: maplibre and mapbox wlll diverge more over time, so do ngx-maplibre-gl and ngx-mapbox-gl. 
I personally like the idea of optional modules, like for geo-coder.

**Comment by HarelM** [comment]
I think the main reason I removed the geocoder was due to its need for a key and the peer dependency needed that not everyone needs (especially me).
If you are using it and would like to add it back as a separate npm package but part of this repo I'm perfectly fine with that.
Yes, I agree about cherry picking in general.

**Comment by HarelM** [comment]
@aprilmay if you could merge a few more commits from upstream it would help me a lot!
Thanks again for all the hard work!

**Comment by HarelM** [comment]
Relevant features to merge:
Most merges are bump version of libraries, which should be done in a single commit I think and should be simply easy.
There's a bug or two fixes in there.
It should be relatively quick...
https://github.com/Wykks/ngx-mapbox-gl/pull/304
https://github.com/Wykks/ngx-mapbox-gl/pull/305
https://github.com/Wykks/ngx-mapbox-gl/pull/306
https://github.com/Wykks/ngx-mapbox-gl/pull/307
https://github.com/Wykks/ngx-mapbox-gl/pull/312
https://github.com/Wykks/ngx-mapbox-gl/pull/313
https://github.com/Wykks/ngx-mapbox-gl/pull/316
https://github.com/Wykks/ngx-mapbox-gl/pull/318

**Comment by aprilmay** [comment]
I cherry-picked, merged and sent a PR for #316.
Then i also did the same for #313.
But, it looks like the PR now contains both changes, leading to some confusion.
Actually i'm also learning the github PR workflows... i'll stop here and wait for your advice.

Beside, aren't there some changes are minor version bumps, automatically generated by dependabot? Should we do that manually? eg. #305

**Comment by HarelM** [comment]
Thanks for taking this forward!
So besides version updates of dependencies are there more stuff to merge?
I don't know when and if depend bot will run.
I think the best approach would be to simply update the dependencies as much as possible and hopefully this will solve most of the issues...

**Comment by aprilmay** [comment]
Happy to help :)
Just sent another PR for #304 , all the remaining changes you quoted are minor bumps.

**Comment by HarelM** [comment]
Resolved by #10
