### ISSUE TITLE
Move out of yarn

### ISSUE THREAD

**Issue by HarelM** [maplibre/ngx-maplibre-gl#7]
I haven't found a good argument to use it for this simple project.
There's probably a need to add a package.json lock file and remove the yarn one...

**Comment by aprilmay** [comment]
I don't get the reason for this one: yarn is the standard package manager for Angular, no? Wouldn't it make things more complex to get rid of it for this project?

**Comment by HarelM** [comment]
It's not, to my understanding.
I think this is an extra step for every new developer that is not really needed, IMHO.
