### ISSUE TITLE
Makes other libs crash like ag-grid

### ISSUE THREAD

**Issue by jeandat** [maplibre/ngx-maplibre-gl#74]
I was using mapbox-gl and ngx-mapbox-gl. I'm trying to migrate to maplibre. With latest versions (maplibre 2.4.0 and @maplibre/ngx-mapbox-gl 13.0.0), i have hundreds of errors on my project on components not even related to maplibre. Other libs like ag-grid or ngx-translate do not compile anymore. Their directives, pipes, components are not found. 

For instance: 
```
error NG8004: No pipe found with name 'translate'.
<button mat-icon-button (click)="showMapPin(data.ne)" [matTooltip]="'ui.alerting.locateOnMap' | translate" class="la-mat-small" color="accent">
```

Any help would be appreciated. Don't understand how this lib can make others fail.

**Comment by HarelM** [comment]
I don't think this lib creates issues, I'm using it in production without any issues.
I would advise to piblish a stackblitz link if you want help.
