### ISSUE TITLE
Controls created with the included directives aren't destroyed correctly

### ISSUE THREAD

**Issue by tzetter** [maplibre/ngx-maplibre-gl#85]
When the included directives (e.g. `mglFullscreen`)  are used together with the control component the `controlAdded` property of the component isn't updated. This means that the controls aren't removed from the map when the components are destroyed. 

To replicate the issue:

1. Create a conditional fullscreen control component

```html
<mgl-control mglFullscreen *ngIf="visible"></mgl-control>
```

2. Toggle the visibility of the component

```typescript
window.setInterval(() => this.visible = !this.visible, 1000);
```

3. Multiple fullscreen controls appear on the map

My suggested solution to the problem would be to stop relying on `controlAdded` being set and using the map's `hasControl` function instead. 

```typescript
  ngOnDestroy() {
    if (this.mapService.mapInstance.hasControl(this.control)) {
      this.mapService.removeControl(this.control);
    }
```

Let me know if you need any further information or want me to create a PR.

**Comment by HarelM** [comment]
Feel free to submit a PR.
Would be great if you could add a test to cover this issue.
