### ISSUE TITLE
Try to display clusters on the map following your example but they don't appear

### ISSUE THREAD

**Issue by dancatalinciurea** [maplibre/ngx-maplibre-gl#88]
You can see my implementation here https://github.com/dancatalinciurea/AngularMapLibre
I used your example url to fetch data https://maplibre.org/maplibre-gl-js-docs/assets/earthquakes.geojson

The map appears but with no clusters

This is the example i used: https://maplibre.org/ngx-maplibre-gl/demo/ngx-cluster-html

**Comment by HarelM** [comment]
Sorry, I can't debug your code.
You can checkout the demo site to see how to use the cluster code.

**Comment by HarelM** [comment]
@dancatalinciurea can I close this issue? Can you create a minimal reproduction of the issue if not?

**Comment by dancatalinciurea** [comment]
It can be closed
