### ISSUE TITLE
Help: MapKit JS integration with this Library

### ISSUE THREAD

**Issue by Sampath-Lokuge** [maplibre/ngx-maplibre-gl#90]
Hi,

I want to use Apple MapKit JS with my Angular app. Can you tell me how to use that with your library/components? Thanks!

Ref: https://developer.apple.com/documentation/mapkitjs/

**Comment by HarelM** [comment]
This library only works with maplibre-gl-js.

**Comment by Sampath-Lokuge** [comment]
Please let me know how to get this key.

` [style]="'https://api.maptiler.com/maps/streets/style.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL'"`

**Comment by HarelM** [comment]
Go to maptiler and sign up, alternatively, you can use OSM raster tiles instead.

**Comment by Sampath-Lokuge** [comment]
Thanks for the info!
