### ISSUE TITLE
Map does not fill its container -- how to force a resize?

### ISSUE THREAD

**Issue by VictorNorman** [maplibre/ngx-maplibre-gl#92]
I'm sorry to ask this question here, but I don't see any other forum or way to ask for help.

In my "Tour of Trees" app that I'm building now with Ionic over Angular using ngx-maplibre-gl, my screen appears and the map is square -- it does not fill the screen.

You can see that by going to [https://calvin-tree-tours.web.app](https://calvin-tree-tours.web.app) .

My repo is [here](https://github.com/VictorNorman/calvin-trees). 

At this point, the code is quite basic:

home.page.html:
```
<ion-content [fullscreen]="true">

  <mgl-map [style]="'https://api.maptiler.com/maps/streets/style.json?key=ted09kFoNPzbRYuDTi5B'" [zoom]="[14]"
    [center]="center" [bearing]="heading">

    <mgl-control mglGeolocate [positionOptions]="{enableHighAccuracy: true}" [trackUserLocation]="true"
      position="top-left">
    </mgl-control>
    <mgl-control mglNavigation [showCompass]="true" position="bottom-left">
    </mgl-control>
    <mgl-control position="bottom-right">
      Nearby Trees: {{ nearbyTrees.length }}
    </mgl-control>

    <mgl-marker [lngLat]="center">
      <ion-img src="assets/icons/arrow.png" anchor="top-left"></ion-img>
    </mgl-marker>

  </mgl-map>
</ion-content>
```
In home.page.scss:
```
mgl-map {
  width: 100%;
  height: 100%;
}
```

When I have used leaflet and other packages, the recommended example code always had a clause like

`setTimeout(() => map.sendResizeEvent(), 50);`

to force the map to resize itself and fill the container. I was happy to see that no maplibre sample code I've seen had this "hack" in it.  But, now that my map is not filling its container, I'm wondering if I do need such a clause.

Do I?  And, if so, how do I implement that clause?

Thanks. (If there is a better place to ask these questions, please let me know.)

**Comment by HarelM** [comment]
This is probably a css issue.
This hack is not needed.
You should be able to debug this using chrome inspect when the device is connected to your PC.

**Comment by VictorNorman** [comment]
OK: I'll keep fighting with it. Thanks.

**Comment by VictorNorman** [comment]
The problem I'm seeing is described here:

https://github.com/mapbox/mapbox-gl-js/issues/3265

**Comment by VictorNorman** [comment]
For the record my full solution is:

```
  @ViewChild('map') map: MapComponent | null = null;
```

and

```
  ngAfterViewInit() {
    setTimeout(() => this.map!.mapInstance.resize(), 0);
  }
```
So, we do have to do the setTimeout() hack. :-(  But, it works.

**Comment by HarelM** [comment]
This is a 7 year old bug which is completely irrelevant.
I don't use this hack in my app here:
https://github.com/IsraelHikingMap/Site/tree/d43a0655b5bc8dc0e6902188acfa29f3b7f928cf/IsraelHiking.Web
But if you insist on writing this I won't stop you...
