### ISSUE TITLE
Map Component in <div> not displaying map

### ISSUE THREAD

**Issue by rokozeit** [maplibre/ngx-maplibre-gl#94]
Hi,

I am creating a angular component with ngx-maplibre-gl called 'app-maplibre-map'.

Adding it directly to another component or app component works.

```
<app-maplibre-map></app-maplibre-map>
```

Adding it to another component inside a <div> does not display the map anymore.

```
<div *ngIf="condition">
<app-maplibre-map></app-maplibre-map>
</div>

```

same behaviour in this [Stackblitz example](https://stackblitz.com/edit/angular-maplibre-map).

changing 'app.component.html' from

```
<div class="map-container" #map></div>
````

to

```
<div>
<div class="map-container" #map></div>
</div>
```

leads to a non displayed map.

Am I doing something wrong?

**Comment by HarelM** [comment]
I haven't looked deeply into the dev tools, but the container of the map needs to be defined in terms of size. If the size of the map container is 0 you won't see the map, if the size is 0 and the condition changes you need to call a map redraw so the the map will calculate the new size and display accordingly.
Hope that helps...

**Comment by rokozeit** [comment]
Haha, amazing. I am rather new to all this and sometimes miss out. Sorry for bothering. So my solution was to set the <div> height to 100%

html:

```
<div class="map-container">
<app-maplibre-map></app-maplibre-map>
</div>
```

css:

```
.map-container {
  height: 100%;
}

```

Thanks for the help.
